# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "sosi-utplukk-fra-generell-objektkatalog"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "standardisering"
